### ISSUE TITLE
Problem with SD route Linux.

### ISSUE THREAD

**Issue by carcagi** [BullyWiiPlaza/Loadiine-Games-Installer#1]
Hi, if you check https://github.com/BullyWiiPlaza/Loadiine-Games-Installer/blob/master/src/main/java/com/bullywiihacks/loadiine/sdcard/installer/SDCardManager.java you'll find the function getNameCount(), that function is breaking the software on Linux, because Linux distributions mount the SD card to a directory with more than 1 path element,  and the path doesn't represent a root element.
I'm not a Java programmer, but this should be changed or validated in Linux on a different way.
Thanks :)
Forgive the bad English :)

**Comment by BullyWiiPlaza** [comment]
Does it really break on Linux? I changed it to the following:

```
public static boolean isRoot(String directory)
{
    if (SystemUtils.IS_OS_WINDOWS)
    {
        Path path = new File(directory).toPath();

        return path.getNameCount() == 0;
    }

    // We cannot tell
    return true;
}
```

**Comment by carcagi** [comment]
Thanks a lot, But it still happens to me :(. Do Java have some kind of cache or something?
![screenshot_2016-06-09_08-43-37](https://cloud.githubusercontent.com/assets/7891882/15931687/63584890-2e1e-11e6-982e-90ed45827365.png)

**Comment by BullyWiiPlaza** [comment]
I removed the code now, it should no longer happen
